development:
  adapter: sqlite3
  database: db/app.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mustacheme
  username: root
  password: batsoup22155109
  socket: /var/run/mysqld/mysqld.sock