environment: production
chdir: /var/www/ruby/mustache.me/current/
address: 127.0.0.1
user: jakedahn
group: jakedahn
port: 50000
pid: /var/www/ruby/mustache.me/shared/pids/thin.pid
rackup: /var/www/ruby/mustache.me/current/config.ru
log: /var/www/ruby/mustache.me/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true